services:
  - type: web
    name: smart-planner2-clean
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLAUDE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    plan: free 